In [1]:
import numpy as np
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC

In [2]:
iris = datasets.load_iris()
X = iris["data"][:, (2, 3)] # petal length, petal width
y = (iris["target"] == 2).astype(np.float64) # Iris-Virginica

In [3]:
std_scaler = StandardScaler()
X_scaled = std_scaler.fit_transform(X)

In [4]:
svm_clf = LinearSVC(C=1, loss="hinge", random_state=42)
svm_clf.fit(X_scaled, y)

LinearSVC(C=1, loss='hinge', random_state=42)

In [5]:
svm_clf.predict(X_scaled[10].reshape(1,-1))
preds =svm_clf.predict(X_scaled)

In [6]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y, preds)

array([[98,  2],
       [ 4, 46]], dtype=int64)

# Full Dataset

In [7]:
iris = datasets.load_iris()
X = iris["data"]
y = (iris["target"] == 2).astype(np.float64) # Iris-Virginica

In [8]:
std_scaler = StandardScaler()
X_scaled = std_scaler.fit_transform(X)

In [9]:
svm_clf.fit(X_scaled, y)

LinearSVC(C=1, loss='hinge', random_state=42)

In [10]:
predictions = svm_clf.predict(X_scaled)

In [11]:
confusion_matrix(y, predictions)

array([[97,  3],
       [ 1, 49]], dtype=int64)

# Classifying non-linear data using polynomial features

In [12]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.datasets import make_moons
import matplotlib.pyplot as plt

# Generate some data
# X, y = make_moons(n_samples=100, noise=0.15, random_state=42)

# Add in a 3rd degree polynomial set of features
poly_features = PolynomialFeatures(degree=3, include_bias=False)
X_poly = poly_features.fit_transform(X)

# Scale the data
X_poly_scaled = std_scaler.fit_transform(X_poly)

# Create a svm classifier and fit the data
poly_svm_clf = LinearSVC(C=10, loss="hinge", random_state=42)
poly_svm_clf.fit(X_poly_scaled, y)

LinearSVC(C=10, loss='hinge', random_state=42)

In [13]:
polypreds = poly_svm_clf.predict(X_poly_scaled)
confusion_matrix(y, polypreds)

array([[98,  2],
       [ 1, 49]], dtype=int64)

## Using a polynomial kernel

In [14]:
from sklearn.svm import SVC
X_scaled = std_scaler.fit_transform(X)
# Create a classifier with a polynomial kernel of degree 3 and fit this to the data
poly_k_svm_clf = SVC(kernel="poly", degree=8, coef0=1, C=5)
X_poly = poly_k_svm_clf.fit(X_scaled, y)
polykpreds = poly_k_svm_clf.predict(X_scaled)
confusion_matrix(y, polykpreds)

array([[100,   0],
       [  0,  50]], dtype=int64)

## Using a Radial Basis Function (RBF) kernel

In [15]:
rbf_svm_clf = SVC(kernel="rbf", gamma=5, C=1)
rbf_svm_clf.fit(X_scaled, y)
rbfpreds = rbf_svm_clf.predict(X_scaled)
confusion_matrix(y, rbfpreds)

array([[100,   0],
       [  0,  50]], dtype=int64)

# Wine dataset

In [16]:
wine = datasets.load_wine()
wX = wine.data
wy = wine.target

In [17]:
from sklearn.model_selection import train_test_split
wX_train, wX_test, wy_train, wy_test = train_test_split(wX, wy, test_size=0.25, random_state=42)

from sklearn.multiclass import OneVsRestClassifier

ovr_svc_clf = OneVsRestClassifier(SVC(kernel="poly", degree=7, coef0=1, C=5))
ovr_svc_clf.fit(wX_train, wy_train)
wine_preds = ovr_svc_clf.predict(wX_test)
confusion_matrix(wy_test, wine_preds)

array([[15,  0,  0],
       [ 1, 15,  2],
       [ 0,  4,  8]], dtype=int64)

# SVM Regression

In [25]:
from sklearn.svm import LinearSVR
from sklearn.metrics import mean_squared_error

boston = datasets.load_boston()
bX = boston.data
by = boston.target

bX_train, bX_test, by_train, by_test = train_test_split(bX, by, test_size=0.25, random_state=42)

svm_reg = LinearSVR(epsilon=8, random_state=42) # Can explore impact of epsilon
svm_reg.fit(bX_train, by_train)
boston_train_preds = svm_reg.predict(bX_train) # Check fit

lin_mse = mean_squared_error(by_train, boston_train_preds)
lin_rmse = np.sqrt(lin_mse)
lin_rmse

c:\users\agath\appdata\local\programs\python\python37\lib\site-packages\sklearn\svm\_base.py:986: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


6.689326893415916

In [26]:
boston_test_preds = svm_reg.predict(bX_test)
lin_mse = mean_squared_error(by_test, boston_test_preds)
lin_rmse = np.sqrt(lin_mse)
lin_rmse

7.492448639233937

# Decision Trees

In [20]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
# Load the data
iris = load_iris()
X = iris.data[:, 2:]
y = iris.target
# Create a Decision Tree Classifier and fit this to the data
tree_clf = DecisionTreeClassifier(max_depth=2)
tree_clf.fit(X, y)

DecisionTreeClassifier(max_depth=2)

In [21]:
# e.g. for single instances
tree_clf.predict([[ 4.8,  1.8]])
# We can also find out the probability associated with a prediction 
tree_clf.predict_proba([[5, 1.5]])
tree_clf.predict([[5, 1.5]])

array([1])

## Wine data decision tree classification

In [23]:
from sklearn.tree import DecisionTreeClassifier
tree_clf = DecisionTreeClassifier(max_depth=7)
tree_clf.fit(wX_train, wy_train)

DecisionTreeClassifier(max_depth=7)

In [24]:
wine_preds = tree_clf.predict(wX_test)
confusion_matrix(wy_test, wine_preds)

array([[14,  1,  0],
       [ 0, 18,  0],
       [ 1,  0, 11]], dtype=int64)

## Boston data decision tree regression

In [30]:
from sklearn.tree import DecisionTreeRegressor
tree_reg = DecisionTreeRegressor(max_depth=7)
tree_reg.fit(bX_train, by_train)

DecisionTreeRegressor(max_depth=7)

In [31]:
boston_preds = tree_reg.predict(bX_train)
lin_mse = mean_squared_error(by_train, boston_preds)
lin_rmse = np.sqrt(lin_mse)
lin_rmse

1.775740612076669

In [33]:
boston_tree_test_preds = tree_reg.predict(bX_test)
lin_mse = mean_squared_error(by_test, boston_tree_test_preds)
lin_rmse = np.sqrt(lin_mse)
lin_rmse

3.083840618273191